# Numerical Computing With Numpy

### without numpy
 given some climate data for a region, we can now predict what the yield of apples in the region might look like. Here's some sample data.
region  |  temp (F) |   rainfall(mm)  |   humidity(%)
kanto   |    73     |        67       |        43
johto   |    91     |        88       |        64
hoenn   |    87     |        134      |        58
sinnoh  |    102    |        43       |        37
unova   |    69     |        96       |        70





In [20]:


kanto_region=[73 , 67 , 43]
johto_region=[91 , 88 , 43]
hoenn=[87 , 134 , 58]
sinnoh=[102 , 43 , 37]
unova=[69 , 96 , 70]
wts=[0.3,0.2,0.5]

# for x in kanto_region:
    #print(x)

#let's make general function to find out apple yield based on these factors
def apple_yield(region,wts):
    yield_calc=0
    for x,w in zip(region,wts):
        yield_calc=yield_calc+(x*w)
    return yield_calc
apple_yield(kanto_region,wts)


56.8

In [21]:
apple_yield(johto_region,wts)

66.4

In [22]:
apple_yield(hoenn,wts)

81.9

In [23]:
apple_yield(unova,wts)

74.9

# 1-D NUMPY ARRAY

In [26]:
import numpy as np

kanto = np.array([73 , 67 , 43])
kanto


array([73, 67, 43])

In [27]:
wts = np.array([0.3 , 0.2 , 0.5])
wts

array([0.3, 0.2, 0.5])

In [28]:
print(type(kanto))

<class 'numpy.ndarray'>


In [31]:
print(wts[0])

0.3


In [32]:
print(kanto[2])

43


### operating on numpy arrays

In [34]:
# using .dot() we did dot product of 2 arrays
print(np.dot(kanto,wts))

56.8


In [1]:
# did dot product with arithmetic operators and sum() function of numbpy
print((kanto*wts).sum())

NameError: name 'kanto' is not defined

### let's compare time taken using numpy and without

In [1]:
#python list
arr1_list = list(range(1000000))
arr2_list = list(range(1000000,2000000))

#numpy arrays
import numpy as np
arr1_np = np.array(arr1_list)
arr2_np = np.array(arr2_list)


In [5]:
# using list
import time
start_time=time.perf_counter()
result=0
for x,y in zip(arr1_list,arr2_list):
    result = result + (x*y)
result
end_time=time.perf_counter()
print("time taken :",end_time - start_time)

time taken : 0.22582220000003872


In [9]:
# using numpy
import time
start=time.perf_counter()
np.dot(arr1_np,arr2_np)
end=time.perf_counter()
print("time taken :",end-start)


time taken : 0.003511700000217388


# 2-D NUMPY ARRAY

In [34]:
climate_data = np.array([ [73 , 67 , 43 ],
                 [91 , 88 , 64 ],
                 [87 , 134 , 58],
                 [102 , 43 , 37],
                 [69 , 96 , 70 ] ])
# it's a mtrix of 5 rows(for each region) and 3 columns(for temp, rainfall, humidity)

In [22]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [23]:
climate_data.shape

(5, 3)

In [26]:
wts=np.array([0.3 , 0.2 , 0.5])

In [27]:
wts.shape

(3,)

# 3-D NUMPY ARRAY

In [30]:
array_3d=np.array([[[11,12,13],
                    [14,15,16]],

                   [[20,21,22],
                    [23,24,25]]])

In [31]:
array_3d

array([[[11, 12, 13],
        [14, 15, 16]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [32]:
array_3d.shape

(2, 2, 3)

In [35]:
array_3d.dtype

dtype('int64')

In [40]:
# checking what happens when we give more col then in other rows
ar = np.array([[1,2,3,],
      [5,6,7,8]])
ar

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [37]:
ar.shape

AttributeError: 'list' object has no attribute 'shape'

# MATRIX MULTIPLICATION

In [42]:
# 2-d matrix
array_2d = np.array ([[1,2,3,4],
                      [5,6,7,8],
                     [9,10,11,12],
                     [13,14,15,16]])


In [43]:
wts=np.array([0.3,0.5,0.1,0.1])


In [45]:
np.matmul(array_2d,wts)

array([ 2.,  6., 10., 14.])

In [46]:
arr=np.array([[73,67,43],
              [91,88,64],
              [87,134,58],
              [102,43,37],
              [69,96,70]])

In [47]:
weights=np.array([0.3,0.2,0.5])

In [48]:
np.matmul(arr,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [49]:
arr @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

# NOTES

In [ ]:
# arrays must be of rows with equal length
# array_name.shape -> shape length of array, returns number of rows and columns 
# array_name.dtype -> tells datatype of an array
# if %%time don't work -> use import time the start and end time using time.perf_counter()
# use np.dot(value1 , value2)
# in numpy array if even 1 element is float then all elements are also converted to float
# np.matmul(val1,val2)   OR  val1 @ val2  -> for matrix multiplication

# Working with CSV data diles

CSV -> comma separated values
is a
- simple text fle
- used to store in tabular format like spreadsheet / database tables
- values separated by comma ,
- file type -> text file
- extension -> .csv
-rows separate by lines
 columns separate by comma

In [81]:
#import urllib.request

#urllib.request.urlretrieve(
#   "D:\MySQL\python for data analysis\India_weather_data.csv" , "climate.txt")

# THIS WILL NOT WORK FOR LOCAL FILES

In [5]:
import numpy as np
climate_data = np.genfromtxt("Bank_Personal_Loan_dataset.csv",delimiter=',',skip_header=1)

FileNotFoundError: Bank_Personal_Loan_dataset.csv not found.

In [83]:
climate_data.dtype


dtype('float64')

In [84]:
climate_data

array([[27.3, 12.9,  9. ],
       [26.8, 12.8,  9.8],
       [26.4, 13. ,  9.4],
       ...,
       [29.2, 16.4, 10.2],
       [29.4, 15.9, 11.2],
       [29.5, 16.3,  9.4]], shape=(8766, 3))

In [85]:
climate_data.shape

(8766, 3)

In [86]:
# now let's predict yield of apple , considering weights
weights = np.array([0.3,0.2,0.5])

In [87]:
weights.shape

(3,)

In [88]:
yield_calc = climate_data @ weights        # matrix multiplication

In [89]:
yield_calc

array([15.27, 15.5 , 15.22, ..., 17.14, 17.6 , 16.81], shape=(8766,))

In [90]:
yield_calc.shape

(8766,)

In [91]:
# we can now add yields(result) back to climate_data(file) as a fourth column using np.concatenate function
# np.concatenate(dataset, yields , where to add row/col -> axis = 1 for col and 0 for row
climate_result = np.concatenate((climate_data, yield_calc.reshape(8766,1)) , axis = 1)
climate_result

array([[27.3 , 12.9 ,  9.  , 15.27],
       [26.8 , 12.8 ,  9.8 , 15.5 ],
       [26.4 , 13.  ,  9.4 , 15.22],
       ...,
       [29.2 , 16.4 , 10.2 , 17.14],
       [29.4 , 15.9 , 11.2 , 17.6 ],
       [29.5 , 16.3 ,  9.4 , 16.81]], shape=(8766, 4))

In [95]:
# WRITING/SAVING RESSULT IN THE FILE
np.savetxt("climate_result.csv",climate_result, delimiter="," ,fmt="%.2f" , header ="Temp_Max,Temp_Min,Windspeed_Max,Yield_apples")

# NOTES

In [96]:
# np.genfromtxt("file/path_name",delimiter=",or;oretc",skip_header=1)   -> file se data ko lene ke liye
#assign wts (kis feature ko kitni imp deni hahi)
# matrix multiplication @
# np.conactenate function -> np.concatenate((datasetname,resultorcalculated_col_name.reshape(matmul_size,1)),axis=1)
# np.savetxt -> to save result to the file
# np.savetxt("file_name_toBeSaved" , final_result_name , delimiter="," , fmt="%.2f" , header="column,names,and,newcolName", comments=" ")

# Arithmetic operations and broadcating


In [1]:
# Numpy supports arithmetic operators like +,-,* etc.

In [2]:
import numpy as np

arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,1,2,3]])
arr3 = np.array([[11,12,13,14],
                 [15,16,17,18],
                 [19,11,12,13]])


In [3]:
arr2=arr2 + 3

In [4]:
arr2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [5]:
arr3 - arr2

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [6]:
arr2/2

array([[2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5],
       [6. , 2. , 2.5, 3. ]])

In [7]:
arr2 * 2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24,  8, 10, 12]])

In [8]:
arr2 % 4

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 0, 1, 2]])

In [9]:
arr2 // 2

array([[2, 2, 3, 3],
       [4, 4, 5, 5],
       [6, 2, 2, 3]])

# Broadcating -> arithmetic operations possible if different dimensions but comapatible shape

In [12]:
arr4 = np.array([[1,2,3,4],                             # 2=D
                [5,6,7,8],
                [9,10,11,12]])

In [13]:
arr4.shape

(3, 4)

In [20]:
arr5=np.array([4,5,6,7])                                  # 1-D

In [21]:
arr5.shape

(4,)

In [19]:
arr4 + arr5

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19]])

In [22]:
# so basically arr4 ruen to be (([4,5,6,7],
#                                [4,5,6,7],
#                                [4,5,6,7],
#                                [4,5,6,7]])

In [24]:
arr_3D = np.array([[[1,2,3,4],
                    [5,6,7,8]],
                   [[9,10,11,12],
                    [13,14,15,16]]])
                   

In [25]:
arr_3D.shape         (layers , row , col)

(2, 2, 4)

# Comparison Operator in Numpy With arrays

In [30]:
array = np.array([[1,2,3,4],        # , is optinal, it dosn's affects shape of an array
                    [3,4,5,6]])


In [28]:
array.shape

(2, 3)

In [31]:
arr_c_1 = np.array([[1,2,3],
                    [3,4,5]])


In [32]:
arr_c_2 = np.array([[2,2,3],
                    [1,2,5]])

In [39]:
arr_c_1 == arr_c_2

array([[False,  True,  True],
       [False, False,  True]])

In [34]:
arr_c_1 != arr_c_2

array([[ True, False, False],
       [ True,  True, False]])

In [35]:
arr_c_1 < arr_c_2

array([[ True, False, False],
       [False, False, False]])

In [36]:
arr_c_1 > arr_c_2

array([[False, False, False],
       [ True,  True, False]])

In [37]:
arr_c_1 >= arr_c_2

array([[False,  True,  True],
       [ True,  True,  True]])

In [38]:
arr_c_1 <= arr_c_2

array([[ True,  True,  True],
       [False, False,  True]])

In [40]:
(arr_c_1 >= arr_c_2).dtype

dtype('bool')

### Now counting number of equal elements in 2 arrays

In [41]:
arr_c_1 = np.array([[1,2,3],
                    [3,4,5]])
arr_c_2 = np.array([[2,2,3],
                    [1,2,5]])

In [42]:
(arr_c_1 == arr_c_2).sum()

np.int64(3)

# NOTES

In [72]:
# Arithmetic op -> +, -, *, /, //, % 
# Broadcasting -> diiferent dimension but same shape -> artihmetic valid and can be applied 1d ko internally 2d bna ke operation krta hai
# 2D shape (row,col)    and  1D shape (ele,) i.e no row no col
# 1D - (no. of ele,)
# 2D - (no. of row,no. of col)
# 3D - (no. of layer,no. of row,no. of col)
# a=np.array([1,2,3,]) or a=np.array([1,2,3])   -> no diffenrence in shape comma is optional makes no effect
# np.array([[1,2,3,4],
#           [5,6,7]])      inhomogenous shape error ( bcz row length is diffferent )
# Comparison op -> == , != , < , > , <= , >=
# in comparison -> dtype is bool and matrix formed is matrix of boolean values
# (arr1 == arr2).sum()  -> to coun no. of equal elements in 2 arrays
# False -> 0
# True -> 1
# INDEXING
#                        col0  col1  col2   col3
# arr3d = np.array ( [ [[ 1  ,  2  ,  3  ,  4],                row0    |>
#                       [5   ,  6  ,  7  ,  8  ]],               row1    |> layer 1
#
#                       [[9  ,  10  ,  11  ,  12],            row0    |> 
#                       [13  ,  14  ,  15  ,  16]],           row1    |> layer 2
#
#                       [[17  ,  18  ,  19  ,  20],           row0    |> layer 3
#                       [21  ,  22  ,  23  ,  24]] ] )        row1    |>
#(slicing,slicing,slicing) -> no dimension reduction
#(slicning,ele,_)  -> dimension reduction -> no. of ele = no of dimensions reduced
# (:) -> return all
# when you give extra index than in array -> index error

# Array indexing and slicing

In [73]:
arr3D = np.array([ [[11,12,13,14],
                    [13,14,15,19]],

                   [[15,16,17,21],
                    [63,92,36,18]],

                   [[98,32,81,23],
                    [17,18,19,43]] ])

In [48]:
arr3D.shape

(3, 2, 4)

In [49]:
# Single Element
arr3D[ 1 , 1 , 3]

np.int64(18)

In [51]:
# arr3D[ 1 , 1 , 4]      # out of bound error since 4 index not exist

In [52]:
# Subarrays using ranges
arr3D[ 1: ]

array([[[15, 16, 17, 21],
        [63, 92, 36, 18]],

       [[98, 32, 81, 23],
        [17, 18, 19, 43]]])

In [54]:
arr3D[ 1: , 0:1 , :2]

array([[[15, 16]],

       [[98, 32]]])

In [56]:
(arr3D[ 1: , 0:1 , :2]).shape        # range preserves dimensions

(2, 1, 2)

In [57]:
arr3D[ 1: , 1 , 3 ]

array([18, 43])

In [58]:
arr3D[ 1: , 1 , :3 ]

array([[63, 92, 36],
       [17, 18, 19]])

In [62]:
arr3D[2]

array([[98, 32, 81, 23],
       [17, 18, 19, 43]])

In [64]:
arr3D[ : , :1 , 1 ]

array([[12],
       [16],
       [32]])

In [66]:
arr3D[ : , :1 ]

array([[[11, 12, 13, 14]],

       [[15, 16, 17, 21]],

       [[98, 32, 81, 23]]])

In [71]:
# arr3D[1,1,3,1] # error too many indices for array

# others ways of creating an array

### # ALL ZEROES

In [79]:

np.zeros((3))

array([0., 0., 0.])

In [80]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [82]:
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### ALL ONES

In [83]:


np.ones((2))

array([1., 1.])

In [93]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [94]:
np.ones([3,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### identity matrix

In [95]:
np.eye(3)      # or np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [105]:
np.eye(3,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

### Random vector

In [107]:
np.random.rand(5)

array([0.84092415, 0.57012461, 0.47355002, 0.75901345, 0.30713109])

In [108]:
np.random.rand(2,4)

array([[0.73882195, 0.59342555, 0.33206192, 0.24980148],
       [0.53906596, 0.73624307, 0.91030536, 0.74419945]])

In [109]:
np.random.rand(2,2,3)

array([[[0.11789009, 0.77997833, 0.28571427],
        [0.94353177, 0.91009008, 0.54590542]],

       [[0.26392864, 0.48469944, 0.18261392],
        [0.19263134, 0.89071686, 0.26433343]]])

### Random Matrix

In [110]:
np.random.randn(5)

array([ 0.32948724,  1.45447974, -4.79306154,  0.81582566,  0.63791303])

In [111]:
np.random.randn(2,3)

array([[ 0.50351632, -0.88723826,  0.6798127 ],
       [-0.30289885,  0.20868715,  1.12163416]])

In [112]:
np.random.randn(2,3,2)

array([[[ 0.84712981, -0.23899808],
        [-0.92767722,  1.06517524],
        [-0.04398265,  0.58808588]],

       [[-1.59855961, -0.59432232],
        [-0.9351693 , -0.93797486],
        [ 1.48877955, -0.31141523]]])

### creating Array with fixed values

In [119]:
np.full((3),3)

array([3, 3, 3])

In [2]:
import numpy as np
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [117]:
np.full((2,2,3),42)

array([[[42, 42, 42],
        [42, 42, 42]],

       [[42, 42, 42],
        [42, 42, 42]]])

### Range with start, end and step

In [121]:
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [127]:
(np.arange(10,90,3)).shape

(27,)

In [124]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [126]:
np.arange(10,90,3).reshape(1,27)

array([[10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55,
        58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88]])

In [128]:
np.arange(10,50,4)

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [129]:
(np.arange(10,50,4)).shape

(10,)

In [132]:
# np.arange(10,50,4).reshape(4,3) # value error

### Equally spaced nos. in a range

In [134]:
np.linspace(10,90,20)

array([10.        , 14.21052632, 18.42105263, 22.63157895, 26.84210526,
       31.05263158, 35.26315789, 39.47368421, 43.68421053, 47.89473684,
       52.10526316, 56.31578947, 60.52631579, 64.73684211, 68.94736842,
       73.15789474, 77.36842105, 81.57894737, 85.78947368, 90.        ])

In [135]:
np.linspace(10,50,5)

array([10., 20., 30., 40., 50.])

In [136]:
np.linspace(10,50,13)

array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
       26.66666667, 30.        , 33.33333333, 36.66666667, 40.        ,
       43.33333333, 46.66666667, 50.        ])

In [137]:
np.linspace(10,20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])